### ISSUE TITLE
Add smooth-scroll class to links?

### ISSUE THREAD

**Issue by Alexander-LIT** [mtoensing/simpletoc#1]
Hello Marc,
thank you for a great plugin!

In the sea of WordPress Plugins that are overloaded with features it is nice to find something lightweight that does the job.

Now for my question:
My theme has a built in smooth scroll function that is triggered by adding `class="smooth-scroll" `to the `<a>` tag. 
Is there an easy way to make simpletoc output the extra class on it's links?

Thanks in advance,
Alex

**Comment by mtoensing** [comment]
Hi Alex,

if I would add an option you would have to switch it on for each instance of SimpleTOC. And if I would add the class to each link automatically it would be bloated.

the best solution is to tell your plug-in that it should select this:

` .simpletoc li a`

This would add smooth scrolling for all your links in SimpleTOC.

What plug-in are you using for smooth scrolling? May there is even a more clever way.

**Comment by Alexander-LIT** [comment]
Hi Marc,

thanks for replying. I am not using a plugin, but my theme "GeneratePress" Premium has it built in, and I don't think there is an option to add extra classes for the scroll function.

**Comment by mtoensing** [comment]
hold my beer.

**Comment by mtoensing** [comment]
Could you please test this version? https://github.com/mtoensing/simpletoc/archive/smooth-scroll.zip There is an option to add the classes. Does it work?

**Comment by mtoensing** [comment]
And please send me a link to the website if it works or if it does not work.

**Comment by Alexander-LIT** [comment]
You sir, are a wizard! 
It works perfectly. Thank you so much. 

Sadly I do not yet have a link to the site as I am still working on it locally. 

The only thing that I noticed was that in the toc settings, it says that it will add the class “smooth_scroll” instead of “smooth-scroll” (which is the class that gets added correctly). This might be a bit confusing to users.

**Comment by mtoensing** [comment]
Fixed. Thanks. Please update to 4.5 from within WordPress.
