### ISSUE TITLE
[Feature request] Ignoring headers in custom blocks

### ISSUE THREAD

**Issue by rafaucau** [mtoensing/simpletoc#20]
I' m using header blocks inside my own block and I don't want it added to the table of contents.

It would be nice if there was an option to ignore specific parent blocks.
E.g.
```php
add_filter( 'simpletoc_ignored_blocks', function ( array $blocks ) {
	$blocks[] = 'my/custom-block';

	return $blocks;
} );
```

**Comment by mtoensing** [comment]
Feel free to provide a pull request. :)
