### ISSUE TITLE
Block Wrapper

### ISSUE THREAD

**Issue by rafaucau** [mtoensing/simpletoc#24]
Currently the table of contents is wrapped with `<div>` only if it has an additional class.
Couldn't it be that this div renders always? This would give theme developers more options for styling this block. Currently, for example, you can't even add a border to the table of contents.
![image](https://user-images.githubusercontent.com/25438601/196050902-fb71f744-ffec-453a-8769-00125b6fd006.png)
Alternatively, I can send a PR to add the appropriate filter. But I think it is better and simpler to just always render this div.

**Comment by mtoensing** [comment]
This was a conscious decision because this way the TOC will be rendered just like a list and a heading. If we would put it in an additional div-wrapper some themes have problems.
