### ISSUE TITLE
Exclude certain headings?

### ISSUE THREAD

**Issue by blronaldhuereca** [mtoensing/simpletoc#26]
Is there a way to exclude headings from being output? If not, would you be open to a PR?

**Comment by mtoensing** [comment]
I cleaned up the FAQ in the [readme](https://github.com/mtoensing/simpletoc/blob/master/readme.txt) to make it clear how to do that. There are at least two ways to that: manually by adding a class and a programmatic approach with filters.

**Comment by blronaldhuereca** [comment]
Thank you 🙏
