### ISSUE TITLE
[Feature Request] Add option to change TOC block heading

### ISSUE THREAD

**Issue by StuxieDev** [mtoensing/simpletoc#27]
Hi there,

This is a simple request to add an option to change the TOC block heading type.

It currently uses H2 by default, but on my site, my default heading is H1.

A simple drop down to select either h1,h2,h3,h4,h5 or h6 as the block heading type would be ideal.

Thanks,

Stux.

**Comment by mtoensing** [comment]
I understand the request. But h1 for more than the posts title is wrong. But you can disable the heading and add a custom h1 heading block and group the result.
