### ISSUE TITLE
[Request] - Ability to hide GenerateBlocks headings

### ISSUE THREAD

**Issue by blronaldhuereca** [mtoensing/simpletoc#28]
Hi again. I saw in the code that the plugin supports GenerateBlocks (very cool).

Is there a way to hide these from the TOC as well using the `simpletoc-hidden` class?

Thanks!

**Comment by mtoensing** [comment]
Have you tried to add that class ?

**Comment by mtoensing** [comment]
Of course :)

**Comment by mtoensing** [comment]
Thank you!
