### ISSUE TITLE
Ability to disable "Hide in accordion menu" option

### ISSUE THREAD

**Issue by rafaucau** [mtoensing/simpletoc#32]
For example, in my own theme I have already made my own accordion, with my own scripts.
It would be useful if there was an option to block this option so that editors could not use it to break a site.

This could be another filter for developers.

**Comment by rafaucau** [comment]
BTW this option makes this plugin incompatible with [AMP](https://wordpress.org/plugins/amp/)
![image](https://user-images.githubusercontent.com/25438601/205463663-2f98335d-abd2-4335-980c-46b721bd4d70.png)

**Comment by mtoensing** [comment]
Please provide a pull request :)

**Comment by mtoensing** [comment]
And for me, the plugin still works with AMP and passes all tests with the accordion menu present in that post. The JS is just missing. I use "Accelerated Mobile Pages" for the AMP plugin.

**Comment by rafaucau** [comment]
> The JS is just missing.

When there is no JS, it is impossible to expand the table of contents.
On AMP, you can show the regular version of the TOC, or use `amp-bind` to make it work.

> Please provide a pull request :)

I will provide a PR in a near future.

**Comment by mtoensing** [comment]
Mine is expanded: https://marc.tv/rollladenschalter-shelly-alexa/amp/ 

![Screenshot 2022-12-07 at 13 29 25](https://user-images.githubusercontent.com/136737/206179657-31a3a4de-e1db-49b0-b371-1ad73dd662f3.png)

**Comment by rafaucau** [comment]
In my case, AMP does not remove the styles of this plugin, so it is collapsed and impossible to expand.

**Comment by rafaucau** [comment]
> I will provide a PR in a near future.

In the SEO plugin I use (Rank Math) they added a table of contents block, so I no longer use that plugin. Sorry
