### ISSUE TITLE
Custom anchor does not work when heading block is a inner block

### ISSUE THREAD

**Issue by rafaucau** [mtoensing/simpletoc#33]
To reproduce:
- Add a heading block and set a custom anchor for it
- Add a group block, for example, and add a heading block inside and set a custom anchor for it
- The link in the TOC to the first block works, to the second one does not

Editor:
![image](https://user-images.githubusercontent.com/25438601/206718677-fd5a71de-abf4-4b82-b829-aa71207a7a5c.png)

Frontend:
![image](https://user-images.githubusercontent.com/25438601/206718857-c53b9db5-e2f1-4090-a5e3-672574e961ed.png)
![image](https://user-images.githubusercontent.com/25438601/206718940-2ed62e80-0d10-42c3-8ec2-a5f81d67b71f.png)

**Comment by mtoensing** [comment]
Does this work if you disable SimpleTOC? Because this is a core function.

**Comment by rafaucau** [comment]
This is the problem with SimpleTOC. The anchor is the one I set in the editor, but Simpletoc tries to use the one generated by itself.

**Comment by mtoensing** [comment]
I see. At first glance this line does not work within groups: https://github.com/mtoensing/simpletoc/blob/master/plugin.php#L461 I will look into this next week

**Comment by mtoensing** [comment]
Maybe you know a fix for that since you have the setup running?

**Comment by rafaucau** [comment]
I'm trying to understand what's going on here. Why is the DOM being used here when `$headline` is just a string?
![image](https://user-images.githubusercontent.com/25438601/206806414-79698dc0-26df-4bbd-b83e-4131d37bd276.png)

**Comment by mtoensing** [comment]
Hi @rafaucau I refactored the plug-in. Maybe you can have a look again. Or I will will look into this feature / bug in the future. Sorry for the delay.

**Comment by mtoensing** [comment]
I think this is fixed
