### ISSUE TITLE
Suggestion: Replace the h2 heading of the TOC with summary

### ISSUE THREAD

**Issue by andremenrath** [mtoensing/simpletoc#38]
I would suggest replacing the `<h2>` element of the toc heading with a `<summary>`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

**Comment by mtoensing** [comment]
Headings are automatically styled in every theme. Summary is the WordPress "Summary" field of each post and is used in other places. Look at the example. The summary is not "table of contents" That is the headline of the toc. The toc is a navigation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav  which is an option in SimpleTOC.

**Comment by andremenrath** [comment]
I see the point where potential conflicts might arise. Thanks for pointing them out! Still I am a fan, of handling TOCs this way, like for example the hugo papermod theme does: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
