### ISSUE TITLE
Make simpleTOC work with sticky headers 

### ISSUE THREAD

**Issue by github-ccnt-nib** [mtoensing/simpletoc#39]
Hi, thanks for the great -no thrills, just works- TOC plugin. 
I have a suggestion to make it much better with sticky headers. 
Add 		

`$tag->setAttribute("style", "display: block; margin-top: -235px; padding-top: 235px;");`

below line 397 of plugin.php, but to *really* shine, make the number 235 configurable (possibly to become any size expression). 
I can then configure the size (e.g. in pixel) of my sticky header and link to a position of the page, such that the anchor is showing just below my sticky header and not underneath it ;-)

**Comment by mtoensing** [comment]
This special task can easily be done with custom css. I really would like to keep SimpleTOC as simple as possile.
