### ISSUE TITLE
Duplicate icon displaying then dissapearing

### ISSUE THREAD

**Issue by joshspires** [mtoensing/simpletoc#44]
**Issue**
Often when opening a post that has the SimpleTOC plugin active two + icons display for a second or two and then one of them disappears.

Using Chrome Dev Tools, I was able to see what the issue was, but not sure of the cause. It appears that the icon is displayed using ::after on `<span class="simpletoc-icon"></span>`. While the page is still loading in 100%, the icon is duplicated to `<button class="simpletoc-collapsible"></button>` element one level up.

This is the website I am testing it on: [https://sffgeek.com/2023/10/08/jonsbo-n3-8-bay-nas-gpu-pc-case/](https://sffgeek.com/2023/10/08/jonsbo-n3-8-bay-nas-gpu-pc-case/)

I have attached an image of the issue, as well as the ::after in the linked to the button element.

![Screenshot 2023-10-08 194521](https://github.com/mtoensing/simpletoc/assets/24408714/79927c28-4378-4d23-9529-3be9363bf891)
![Screenshot 2023-10-08 195555](https://github.com/mtoensing/simpletoc/assets/24408714/7094bb0f-8511-4b93-9a35-fac99e1e6c7f)

**Version and device info**
- WordPress v6.3.1
- Twenty Twenty-Three theme v1.2
- SimpleTOC v6.0.10
- Chrome build 117.0.5938.149
- Windows 11 build 22631.2338

**Comment by mtoensing** [comment]
Can you please check if this is a problem on your site with another theme? Because I am not able to reproduce this
