### ISSUE TITLE
Match icon colour to WordPress theme colour

### ISSUE THREAD

**Issue by joshspires** [mtoensing/simpletoc#45]
**Idea**
Instead of using the default purple colour (#635994) as the colour for the + and - icon, it would be a nice touch to have it use the WordPress default theme colours selected by the user.

WordPress includes the following CSS variables:

```
    --wp--preset--color--base: #ffffff;
    --wp--preset--color--contrast: #000000;
    --wp--preset--color--primary: #2195ff;
    --wp--preset--color--secondary: #004382;
    --wp--preset--color--tertiary: #F6F6F6;
```

**Comment by mtoensing** [comment]
Good idea. The problem is the way the + cannot be colored using just a "color" attribute in css. It is always black. =/ You can send a pull request if you like on github.
