### ISSUE TITLE
Use only H2  headings?

### ISSUE THREAD

**Issue by alvarotrigo** [mtoensing/simpletoc#49]
It'd be nice to have the option to hide all H3, H4, etc.

It's just a single option more and probably you can deal with it on the PHP side?
So still, no JS or fancy stuff is required. 

I quite like this plugin because of its simplicity and no dependencies philosophy, but I can't just add all those long H3s everywhere.
Specially if I want to add this plugin on a fixed navigation on the side.

**Comment by mtoensing** [comment]
But you can do that. You can limit the "depth".

**Comment by alvarotrigo** [comment]
Where exactly?

<img width="956" alt="image" src="https://github.com/mtoensing/simpletoc/assets/1706326/ceba47de-8a5d-41c3-ad5e-e7498fc733ed">

**Comment by mtoensing** [comment]
It is a Blog level setting. Use a „reusable block“ to make this setting persistent.

**Comment by alvarotrigo** [comment]
I see, so if we want to filter by headings, we have to manually change the setting on the TOC of every single blog post?

**Comment by mtoensing** [comment]
No, use the SimpleTOC block in a reusable block after you configured it according to your needs. See the faq pls

**Comment by alvarotrigo** [comment]
Ok thanks.
