### ISSUE TITLE
Suggestion: use details tag without js or css as a "native accordion"

### ISSUE THREAD

**Issue by mtoensing** [mtoensing/simpletoc#57]
The core idea of SimpleTOC is simplicity without compromises. I always disliked the accordion because of the JavaScript that has to be added.

Now @infinitnet [came up](https://wordpress.org/support/topic/feature-request-js-less-accordion/) with a brilliant idea: the details tag: https://www.w3schools.com/tags/tag_details.asp

The solution could look like this and would replace or be the alternative to the accordion:

```
<nav aria-label="Table of Contents">
   <details id="simpletoc-details" class="simpletoc">
      <summary>Table of Contents</summary>
      <div class="simpletoc-content">
         <ul class="simpletoc-list">
            <li><a href="#topic-1">Topic 1</a></li>
            <li><a href="#topic-2">Topic 2</a></li>
            <li><a href="#topic-3">Topic 3</a></li>
            <li><a href="#topic-4">Topic 4</a></li>
            <li><a href="#topic-5">Topic 5</a></li>
            <li><a href="#topic-6">Topic 6</a></li>
            <li><a href="#download">Download</a></li>
         </ul>
      </div>
   </details>
</nav>
```

Are the any suggestions to the markup or general ideas? Especially for the ARIA attributes and the Nav tag?

**Comment by infinitnet** [comment]
I'd wrap only the `<ul>` in `<nav>`. Although it's not technically wrong to include the title or anything other than links in nav tags, it would be a best practice to have them contain nothing but the links according to most documentations. Then I'd consider using `aria-labelledby` for ARIA instead of `aria-label` because you are labelling elements that are visible witin the DOM. "**If there is no content that can be referenced to create an accessible name**, the `aria-label` attribute should be used instead." ([ref](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby))

**Comment by mtoensing** [comment]
Okay, Thanks. May you propose an example like the one above so there are no misunderstandings?

**Comment by infinitnet** [comment]
@mtoensing This is my proposal:

```
<details id="simpletoc-details" class="simpletoc" aria-labelledby="simpletoc-title">
   <summary id="simpletoc-title">Table of Contents</summary>
   <div class="simpletoc-content">
      <nav>
         <ul class="simpletoc-list">
            <li><a href="#topic-1">Topic 1</a></li>
            <li><a href="#topic-2">Topic 2</a></li>
            <li><a href="#topic-3">Topic 3</a></li>
            <li><a href="#topic-4">Topic 4</a></li>
            <li><a href="#topic-5">Topic 5</a></li>
            <li><a href="#topic-6">Topic 6</a></li>
            <li><a href="#download">Download</a></li>
         </ul>
      </nav>
   </div>
</details>
```

**Comment by mtoensing** [comment]
Thanks for the proposal. I understand the idea to put the nav inside the details tag. 

Regarding the options: I think that an entry in the faq on how to style the details tag is worth more than an option where you can change the icon. My experience from things like that is that the next person wants more than the icon. So my guide for an option is: Does it change the functionality? If so, it is okay. Does it only change the appearance in the frontend? Think twice if CSS isn't the better and more versatile solution. So I would start with a non styled version without css. I know that at least a

`cursor: pointer`

would be good but I'd like to start simple. Thanks for your input so far. Much appreciated.

**Comment by infinitnet** [comment]
This approach makes sense indeed. And the cursor not being a pointer on hover of details tags is something I didn't think of, which would indeed make sense to consider as a default as well _if_ you start adding CSS. Thanks for your quick and positive feedback as well.

**Comment by mtoensing** [comment]
Do you mind to beta test 6.5.0? https://github.com/mtoensing/simpletoc/archive/refs/heads/master.zip @infinitnet

**Comment by mtoensing** [comment]
Maybe you @infinitnet could add a FAQ section in the readme on how to style it with css if you like =)

**Comment by mtoensing** [comment]
Still needs testing

**Comment by infinitnet** [comment]
@mtoensing I just briefly tested 6.5.0 and it works well. The only thing I noticed is that the nav tags are missing even with the wrapper div enabled. Not sure if this is intentional or an error. Other than that it looks great!

**Comment by mtoensing** [comment]
The reason for the markup is that there is already an option in place to add a wrapper with the role navigation. This works for all states of the TOC: normal, accordion, details. That is the reason why I did not tackle this. Thanks for testing!
