### ISSUE TITLE
Function wp_enqueue_script() was called incorrectly when opening Appearance > Widgets

### ISSUE THREAD

**Issue by oldrup** [mtoensing/simpletoc#59]
Hey!

I get the following notice, when I go to Appearance > Widgets, having WP-DEBUG and SimpleTOC enabled.

` Notice: Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.) in /example.net/wp-includes/functions.php on line 6078`

![image](https://github.com/mtoensing/simpletoc/assets/17141205/82f387f2-08a3-42c7-b765-e137c8c43d2a)

If I disable SimpleTOC the notice goes away.

WP 6.5 and PHP 8.2

Is that something you can reproduce?

Best regards,
Bjarne

**Comment by mtoensing** [comment]
Widgets are deprecated. In a normal WordPress installation there is no entry "Widgets" anymore. Please check why this entry is still visible for you.

**Comment by oldrup** [comment]
> Widgets are deprecated. In a normal WordPress installation there is no entry "Widgets" anymore. Please check why this entry is still visible for you.

Ah, okay, must be because I'm using a classic (not FSE) theme still. Thank you!

**Comment by mtoensing** [comment]
Please remove classic. It is over. Gutenberg is the future.

**Comment by oldrup** [comment]
Oh, I'm using Gutenberg for content, for sure. I'm still maintaining numerous legacy sites, though. But will test with a core theme next time before posting any issues. I completely respect you cannot support old tech forever.
